# Generated by Django 5.0.7 on 2024-07-31 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_candidate_company_postjob_usermaster_delete_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Salary', models.CharField(max_length=200)),
                ('resume', models.FileField(upload_to='app/resume')),
                ('gender', models.CharField(max_length=200)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.postjob')),
            ],
        ),
    ]
