# Generated by Django 5.0.7 on 2024-08-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_applyjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='experiences',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='applyjob',
            name='jobname',
            field=models.CharField(default=0, max_length=250),
        ),
        migrations.AddField(
            model_name='applyjob',
            name='location',
            field=models.CharField(default=0, max_length=250),
        ),
    ]
