# Generated by Django 5.0.7 on 2024-08-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_applyjob_experiences_applyjob_jobname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjob',
            name='logo_pic',
            field=models.ImageField(default=0, upload_to='app/joblogo'),
        ),
    ]
